
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class Project
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.Project
			this.Name = "CustomerManager.Project";
			this.Title = global::Mono.Unix.Catalog.GetString ("Project");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
