
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class ProjectWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.ProjectWindow
			this.Name = "CustomerManager.ProjectWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProjectWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
