
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class ProjectsWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action applyAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action clearAction;
		private global::Gtk.Action dialogQuestionAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Toolbar toolbar2;
		private global::Gtk.Label headerLabel;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Table valueTable;
		private global::Gtk.ComboBox customerCB;
		private global::Gtk.Label customerLabel;
		private global::Gtk.Label endDateLabel;
		private global::Gtk.Label nameLabel;
		private global::Gtk.Button newCustomerButton;
		private global::Gtk.Button newSupplierButton;
		private global::Gtk.Entry projectNameTextBox;
		private global::Gtk.Label startdateLabel;
		private global::Gtk.ComboBox supplierCB;
		private global::Gtk.Label supplierLabel;
		private global::Gtk.ComboBoxEntry userCBE;
		private global::Gtk.Label userLabel;
		private global::Gtk.Table table2;
		private global::Gtk.Label descriptionLabel;
		private global::Gtk.Entry descriptionTextBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.ProjectsWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.applyAction = new global::Gtk.Action ("applyAction", null, null, "gtk-apply");
			w1.Add (this.applyAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", null, null, "gtk-close");
			w1.Add (this.closeAction, null);
			this.clearAction = new global::Gtk.Action ("clearAction", null, null, "gtk-clear");
			w1.Add (this.clearAction, null);
			this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", null, null, "gtk-dialog-question");
			w1.Add (this.dialogQuestionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "CustomerManager.ProjectsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProjectsWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(12));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child CustomerManager.ProjectsWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar2'><toolitem/><toolitem/><toolitem/><toolitem/><toolitem name='applyAction' action='applyAction'/><toolitem name='closeAction' action='closeAction'/><separator/><toolitem name='clearAction' action='clearAction'/><toolitem name='dialogQuestionAction' action='dialogQuestionAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.vbox1.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.headerLabel = new global::Gtk.Label ();
			this.headerLabel.Name = "headerLabel";
			this.headerLabel.Xalign = 0F;
			this.headerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Neues Projekt erstellen:");
			this.vbox1.Add (this.headerLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.headerLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.valueTable = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.valueTable.Name = "valueTable";
			this.valueTable.RowSpacing = ((uint)(6));
			this.valueTable.ColumnSpacing = ((uint)(6));
			// Container child valueTable.Gtk.Table+TableChild
			this.customerCB = global::Gtk.ComboBox.NewText ();
			this.customerCB.Name = "customerCB";
			this.valueTable.Add (this.customerCB);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.valueTable [this.customerCB]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.customerLabel = new global::Gtk.Label ();
			this.customerLabel.Name = "customerLabel";
			this.customerLabel.Xalign = 0F;
			this.customerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Kunde:");
			this.valueTable.Add (this.customerLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.valueTable [this.customerLabel]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.endDateLabel = new global::Gtk.Label ();
			this.endDateLabel.Name = "endDateLabel";
			this.endDateLabel.Xalign = 0F;
			this.endDateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Enddatum: ");
			this.valueTable.Add (this.endDateLabel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.valueTable [this.endDateLabel]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.nameLabel = new global::Gtk.Label ();
			this.nameLabel.Name = "nameLabel";
			this.nameLabel.Xalign = 0F;
			this.nameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Projektname:");
			this.valueTable.Add (this.nameLabel);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.valueTable [this.nameLabel]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.newCustomerButton = new global::Gtk.Button ();
			this.newCustomerButton.CanFocus = true;
			this.newCustomerButton.Name = "newCustomerButton";
			this.newCustomerButton.UseUnderline = true;
			this.newCustomerButton.Label = "neuer Kunde";
			this.valueTable.Add (this.newCustomerButton);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.valueTable [this.newCustomerButton]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.newSupplierButton = new global::Gtk.Button ();
			this.newSupplierButton.CanFocus = true;
			this.newSupplierButton.Name = "newSupplierButton";
			this.newSupplierButton.UseUnderline = true;
			this.newSupplierButton.Label = global::Mono.Unix.Catalog.GetString ("neuer Lieferant");
			this.valueTable.Add (this.newSupplierButton);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.valueTable [this.newSupplierButton]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.projectNameTextBox = new global::Gtk.Entry ();
			this.projectNameTextBox.CanFocus = true;
			this.projectNameTextBox.Name = "projectNameTextBox";
			this.projectNameTextBox.IsEditable = true;
			this.projectNameTextBox.InvisibleChar = '●';
			this.valueTable.Add (this.projectNameTextBox);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.valueTable [this.projectNameTextBox]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.startdateLabel = new global::Gtk.Label ();
			this.startdateLabel.Name = "startdateLabel";
			this.startdateLabel.Xalign = 0F;
			this.startdateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Startdatum:");
			this.valueTable.Add (this.startdateLabel);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.valueTable [this.startdateLabel]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.supplierCB = global::Gtk.ComboBox.NewText ();
			this.supplierCB.Name = "supplierCB";
			this.valueTable.Add (this.supplierCB);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.valueTable [this.supplierCB]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.supplierLabel = new global::Gtk.Label ();
			this.supplierLabel.Name = "supplierLabel";
			this.supplierLabel.Xalign = 0F;
			this.supplierLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Lieferanten:");
			this.valueTable.Add (this.supplierLabel);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.valueTable [this.supplierLabel]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.userCBE = global::Gtk.ComboBoxEntry.NewText ();
			this.userCBE.Name = "userCBE";
			this.valueTable.Add (this.userCBE);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.valueTable [this.userCBE]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child valueTable.Gtk.Table+TableChild
			this.userLabel = new global::Gtk.Label ();
			this.userLabel.Name = "userLabel";
			this.userLabel.Xalign = 0F;
			this.userLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Bearbeiter : ");
			this.valueTable.Add (this.userLabel);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.valueTable [this.userLabel]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.valueTable);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.valueTable]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.descriptionLabel = new global::Gtk.Label ();
			this.descriptionLabel.Name = "descriptionLabel";
			this.descriptionLabel.Xalign = 0F;
			this.descriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Projektbeschreibung :");
			this.table2.Add (this.descriptionLabel);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.descriptionLabel]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.descriptionTextBox = new global::Gtk.Entry ();
			this.descriptionTextBox.CanFocus = true;
			this.descriptionTextBox.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.descriptionTextBox.Name = "descriptionTextBox";
			this.descriptionTextBox.IsEditable = true;
			this.descriptionTextBox.MaxLength = 200;
			this.descriptionTextBox.InvisibleChar = '●';
			this.table2.Add (this.descriptionTextBox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.descriptionTextBox]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(0));
			this.vbox1.Add (this.table2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 430;
			this.DefaultHeight = 350;
			this.Show ();
		}
	}
}
