
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class SupplierTyp
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label4;
		private global::Gtk.Entry typTextBox;
		private global::Gtk.Button save;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.SupplierTyp
			this.Name = "CustomerManager.SupplierTyp";
			this.Title = global::Mono.Unix.Catalog.GetString ("SupplierTyp");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CustomerManager.SupplierTyp.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(21));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Neuer Typ eingeben");
			this.vbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.typTextBox = new global::Gtk.Entry ();
			this.typTextBox.CanFocus = true;
			this.typTextBox.Name = "typTextBox";
			this.typTextBox.IsEditable = true;
			this.typTextBox.InvisibleChar = '●';
			this.vbox1.Add (this.typTextBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.typTextBox]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.save = new global::Gtk.Button ();
			this.save.CanFocus = true;
			this.save.Name = "save";
			this.save.UseUnderline = true;
			this.save.Label = global::Mono.Unix.Catalog.GetString ("speichern...");
			this.vbox1.Add (this.save);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.save]));
			w3.Position = 2;
			w3.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 393;
			this.DefaultHeight = 141;
			this.Show ();
			this.save.Clicked += new global::System.EventHandler (this.OnSaveClicked);
		}
	}
}
