
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class CompanyWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action applyAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action clearAction;
		private global::Gtk.Action dialogQuestionAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.Label headerOneLabel;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Table table1;
		private global::Gtk.Label countryLabel;
		private global::Gtk.Entry countryTextBox;
		private global::Gtk.Label hnrLabel;
		private global::Gtk.Entry hnrTextBox;
		private global::Gtk.Label nameLabel;
		private global::Gtk.Entry nameTextBox;
		private global::Gtk.Label plzLabel;
		private global::Gtk.Entry plzTextBox;
		private global::Gtk.Label streetLabel;
		private global::Gtk.Entry streetTextBox;
		private global::Gtk.ComboBox typComboBox;
		private global::Gtk.Label webLabel;
		private global::Gtk.Entry webTextBox;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label partnerLabel;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Table table3;
		private global::Gtk.Label emailLabel;
		private global::Gtk.Entry emailTextBox;
		private global::Gtk.Label mobilenrLabel;
		private global::Gtk.Entry mobileTextBox;
		private global::Gtk.Entry phoneTextBox;
		private global::Gtk.Label pnameLabel;
		private global::Gtk.Entry pnameTextBox;
		private global::Gtk.Label telnumberLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.CompanyWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.applyAction = new global::Gtk.Action ("applyAction", global::Mono.Unix.Catalog.GetString ("Anwenden"), null, "gtk-apply");
			this.applyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Anwenden");
			w1.Add (this.applyAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("schließen"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("schließen");
			w1.Add (this.closeAction, null);
			this.clearAction = new global::Gtk.Action ("clearAction", global::Mono.Unix.Catalog.GetString ("leeren"), null, "gtk-clear");
			this.clearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("leeren");
			w1.Add (this.clearAction, null);
			this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", global::Mono.Unix.Catalog.GetString ("Hilfe"), null, "gtk-dialog-question");
			this.dialogQuestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hilfe");
			w1.Add (this.dialogQuestionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "CustomerManager.CompanyWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("neues Unernehmen");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_new-bcard", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child CustomerManager.CompanyWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='applyAction' action='applyAction'/><toolitem name='closeAction' action='closeAction'/><separator/><toolitem name='clearAction' action='clearAction'/><toolitem name='dialogQuestionAction' action='dialogQuestionAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.headerOneLabel = new global::Gtk.Label ();
			this.headerOneLabel.HeightRequest = 16;
			this.headerOneLabel.Name = "headerOneLabel";
			this.headerOneLabel.Xalign = 0F;
			this.headerOneLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Daten:");
			this.headerOneLabel.UseUnderline = true;
			this.headerOneLabel.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add (this.headerOneLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.headerOneLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.HeightRequest = 6;
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.countryLabel = new global::Gtk.Label ();
			this.countryLabel.Name = "countryLabel";
			this.countryLabel.Xalign = 0F;
			this.countryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Ort: ");
			this.table1.Add (this.countryLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.countryLabel]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.countryTextBox = new global::Gtk.Entry ();
			this.countryTextBox.CanFocus = true;
			this.countryTextBox.Name = "countryTextBox";
			this.countryTextBox.IsEditable = true;
			this.countryTextBox.InvisibleChar = '●';
			this.table1.Add (this.countryTextBox);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.countryTextBox]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hnrLabel = new global::Gtk.Label ();
			this.hnrLabel.Name = "hnrLabel";
			this.hnrLabel.Xalign = 0F;
			this.hnrLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Hnr.:");
			this.table1.Add (this.hnrLabel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hnrLabel]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hnrTextBox = new global::Gtk.Entry ();
			this.hnrTextBox.CanFocus = true;
			this.hnrTextBox.Name = "hnrTextBox";
			this.hnrTextBox.IsEditable = true;
			this.hnrTextBox.InvisibleChar = '●';
			this.table1.Add (this.hnrTextBox);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.hnrTextBox]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameLabel = new global::Gtk.Label ();
			this.nameLabel.Name = "nameLabel";
			this.nameLabel.Xalign = 0F;
			this.nameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Name: ");
			this.table1.Add (this.nameLabel);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameLabel]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameTextBox = new global::Gtk.Entry ();
			this.nameTextBox.CanFocus = true;
			this.nameTextBox.Name = "nameTextBox";
			this.nameTextBox.IsEditable = true;
			this.nameTextBox.InvisibleChar = '●';
			this.table1.Add (this.nameTextBox);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameTextBox]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.plzLabel = new global::Gtk.Label ();
			this.plzLabel.Name = "plzLabel";
			this.plzLabel.Xalign = 0F;
			this.plzLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("PLZ: ");
			this.table1.Add (this.plzLabel);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.plzLabel]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.plzTextBox = new global::Gtk.Entry ();
			this.plzTextBox.CanFocus = true;
			this.plzTextBox.Name = "plzTextBox";
			this.plzTextBox.IsEditable = true;
			this.plzTextBox.InvisibleChar = '●';
			this.table1.Add (this.plzTextBox);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.plzTextBox]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.streetLabel = new global::Gtk.Label ();
			this.streetLabel.Name = "streetLabel";
			this.streetLabel.Xalign = 0F;
			this.streetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Staße: ");
			this.table1.Add (this.streetLabel);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.streetLabel]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.streetTextBox = new global::Gtk.Entry ();
			this.streetTextBox.CanFocus = true;
			this.streetTextBox.Name = "streetTextBox";
			this.streetTextBox.IsEditable = true;
			this.streetTextBox.InvisibleChar = '●';
			this.table1.Add (this.streetTextBox);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.streetTextBox]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.typComboBox = global::Gtk.ComboBox.NewText ();
			this.typComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Unternehmen"));
			this.typComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Firma"));
			this.typComboBox.Name = "typComboBox";
			this.typComboBox.Active = 0;
			this.table1.Add (this.typComboBox);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.typComboBox]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.webLabel = new global::Gtk.Label ();
			this.webLabel.Name = "webLabel";
			this.webLabel.Xalign = 0F;
			this.webLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Homepage:");
			this.table1.Add (this.webLabel);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.webLabel]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.webTextBox = new global::Gtk.Entry ();
			this.webTextBox.CanFocus = true;
			this.webTextBox.Name = "webTextBox";
			this.webTextBox.IsEditable = true;
			this.webTextBox.InvisibleChar = '●';
			this.table1.Add (this.webTextBox);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.webTextBox]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 21;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.partnerLabel = new global::Gtk.Label ();
			this.partnerLabel.Name = "partnerLabel";
			this.partnerLabel.Xalign = 0F;
			this.partnerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Bezugsperson: (optional)");
			this.vbox1.Add (this.partnerLabel);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.partnerLabel]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.HeightRequest = 6;
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w21.Position = 6;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.emailLabel = new global::Gtk.Label ();
			this.emailLabel.Name = "emailLabel";
			this.emailLabel.Xalign = 0F;
			this.emailLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("E-Mail: ");
			this.table3.Add (this.emailLabel);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.emailLabel]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.emailTextBox = new global::Gtk.Entry ();
			this.emailTextBox.CanFocus = true;
			this.emailTextBox.Name = "emailTextBox";
			this.emailTextBox.IsEditable = true;
			this.emailTextBox.InvisibleChar = '●';
			this.table3.Add (this.emailTextBox);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.emailTextBox]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.mobilenrLabel = new global::Gtk.Label ();
			this.mobilenrLabel.Name = "mobilenrLabel";
			this.mobilenrLabel.Xalign = 0F;
			this.mobilenrLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Mobil:");
			this.table3.Add (this.mobilenrLabel);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.mobilenrLabel]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.mobileTextBox = new global::Gtk.Entry ();
			this.mobileTextBox.CanFocus = true;
			this.mobileTextBox.Name = "mobileTextBox";
			this.mobileTextBox.IsEditable = true;
			this.mobileTextBox.InvisibleChar = '●';
			this.table3.Add (this.mobileTextBox);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.mobileTextBox]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.phoneTextBox = new global::Gtk.Entry ();
			this.phoneTextBox.CanFocus = true;
			this.phoneTextBox.Name = "phoneTextBox";
			this.phoneTextBox.IsEditable = true;
			this.phoneTextBox.InvisibleChar = '●';
			this.table3.Add (this.phoneTextBox);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.phoneTextBox]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.pnameLabel = new global::Gtk.Label ();
			this.pnameLabel.Name = "pnameLabel";
			this.pnameLabel.Xalign = 0F;
			this.pnameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Nachname: ");
			this.table3.Add (this.pnameLabel);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.pnameLabel]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.pnameTextBox = new global::Gtk.Entry ();
			this.pnameTextBox.CanFocus = true;
			this.pnameTextBox.Name = "pnameTextBox";
			this.pnameTextBox.IsEditable = true;
			this.pnameTextBox.InvisibleChar = '●';
			this.table3.Add (this.pnameTextBox);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.pnameTextBox]));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.telnumberLabel = new global::Gtk.Label ();
			this.telnumberLabel.Name = "telnumberLabel";
			this.telnumberLabel.Xalign = 0F;
			this.telnumberLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Tel.:");
			this.table3.Add (this.telnumberLabel);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.telnumberLabel]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
			w30.Position = 7;
			w30.Expand = false;
			w30.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 515;
			this.DefaultHeight = 584;
			this.Show ();
			this.applyAction.Activated += new global::System.EventHandler (this.OnApplyActionActivated);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
			this.clearAction.Activated += new global::System.EventHandler (this.OnClearActionActivated);
			this.dialogQuestionAction.Activated += new global::System.EventHandler (this.OnDialogQuestionActionActivated);
		}
	}
}
