
// This file has been generated by the GUI designer. Do not modify.
namespace CustomerManager
{
	public partial class SpecificWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action dialogInfoAction;
		private global::Gtk.Action DateiAction;
		private global::Gtk.Action ProjekAction;
		private global::Gtk.Action ZeitAction;
		private global::Gtk.Action LieferantAction;
		private global::Gtk.Action KundeAction;
		private global::Gtk.Action RechnungAction;
		private global::Gtk.Action HilfeAction;
		private global::Gtk.Action dialogInfoAction1;
		private global::Gtk.Action printPreviewAction;
		private global::Gtk.Action printAction;
		private global::Gtk.Action editAction1;
		private global::Gtk.Action mediaStopAction;
		private global::Gtk.Action homeAction;
		private global::Gtk.Action addAction;
		private global::Gtk.Action infoAction;
		private global::Gtk.Action infoAction1;
		private global::Gtk.Action editAction;
		private global::Gtk.Action editAction2;
		private global::Gtk.Action printAction1;
		private global::Gtk.Action redoAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.Image image2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label projectTitelLabel;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VBox vbox12;
		private global::Gtk.Label timeLabel;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.Table table3;
		private global::Gtk.Button endButton;
		private global::Gtk.Label endLabel;
		private global::Gtk.Label endtimeLabel;
		private global::Gtk.Button startButton;
		private global::Gtk.Label startLabel;
		private global::Gtk.Label starttimeLabel;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.VBox vbox11;
		private global::Gtk.Label projectdescriptionLabel;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView ProjectDescriptionTextView;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label descriptionLabel;
		private global::Gtk.TextView textview2;
		private global::Gtk.VBox vbox13;
		private global::Gtk.HSeparator hseparator5;
		private global::Gtk.Label terminLabel;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HSeparator hseparator7;
		private global::Gtk.Table table4;
		private global::Gtk.Label eDateLabel;
		private global::Gtk.Label enddateBarLabel;
		private global::Gtk.Label enddateLabel;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label sDateLabel;
		private global::Gtk.Label startdateBarLabel;
		private global::Gtk.Label startdateLabel;
		private global::Gtk.HScale TimeHscale;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label TimesLabel;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.HSeparator hseparator8;
		private global::Gtk.Table table5;
		private global::Gtk.Label gesPriceLabel;
		private global::Gtk.Label hourGesLabel;
		private global::Gtk.Label hourPricegesLabel;
		private global::Gtk.Label hourPriceLabel;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.Label label21;
		private global::Gtk.Label label22;
		private global::Gtk.Label label23;
		private global::Gtk.Label label24;
		private global::Gtk.Label label29;
		private global::Gtk.Label label30;
		private global::Gtk.Label materialPriceLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CustomerManager.SpecificWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("Info"), global::Mono.Unix.Catalog.GetString ("Informationen zum Projekt anzeigen"), "gtk-dialog-info");
			this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Info");
			w1.Add (this.dialogInfoAction, null);
			this.DateiAction = new global::Gtk.Action ("DateiAction", global::Mono.Unix.Catalog.GetString ("Datei"), null, null);
			this.DateiAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Datei");
			w1.Add (this.DateiAction, null);
			this.ProjekAction = new global::Gtk.Action ("ProjekAction", global::Mono.Unix.Catalog.GetString ("Projek"), null, null);
			this.ProjekAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Projek");
			w1.Add (this.ProjekAction, null);
			this.ZeitAction = new global::Gtk.Action ("ZeitAction", global::Mono.Unix.Catalog.GetString ("Zeit"), null, null);
			this.ZeitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zeit");
			w1.Add (this.ZeitAction, null);
			this.LieferantAction = new global::Gtk.Action ("LieferantAction", global::Mono.Unix.Catalog.GetString ("Lieferant"), null, null);
			this.LieferantAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Lieferant");
			w1.Add (this.LieferantAction, null);
			this.KundeAction = new global::Gtk.Action ("KundeAction", global::Mono.Unix.Catalog.GetString ("Kunde"), null, null);
			this.KundeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Kunde");
			w1.Add (this.KundeAction, null);
			this.RechnungAction = new global::Gtk.Action ("RechnungAction", global::Mono.Unix.Catalog.GetString ("Rechnung"), null, null);
			this.RechnungAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rechnung");
			w1.Add (this.RechnungAction, null);
			this.HilfeAction = new global::Gtk.Action ("HilfeAction", global::Mono.Unix.Catalog.GetString ("Hilfe"), null, null);
			this.HilfeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hilfe");
			w1.Add (this.HilfeAction, null);
			this.dialogInfoAction1 = new global::Gtk.Action ("dialogInfoAction1", global::Mono.Unix.Catalog.GetString ("Information"), null, "gtk-dialog-info");
			this.dialogInfoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Information");
			w1.Add (this.dialogInfoAction1, null);
			this.printPreviewAction = new global::Gtk.Action ("printPreviewAction", global::Mono.Unix.Catalog.GetString ("Anzeigen"), null, "gtk-print-preview");
			this.printPreviewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Anzeigen");
			w1.Add (this.printPreviewAction, null);
			this.printAction = new global::Gtk.Action ("printAction", global::Mono.Unix.Catalog.GetString ("_Drucken"), null, "gtk-print");
			this.printAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Drucken");
			w1.Add (this.printAction, null);
			this.editAction1 = new global::Gtk.Action ("editAction1", global::Mono.Unix.Catalog.GetString ("bearbeiten"), null, "gtk-edit");
			this.editAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("bearbeiten");
			w1.Add (this.editAction1, null);
			this.mediaStopAction = new global::Gtk.Action ("mediaStopAction", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-media-stop");
			this.mediaStopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
			w1.Add (this.mediaStopAction, null);
			this.homeAction = new global::Gtk.Action ("homeAction", global::Mono.Unix.Catalog.GetString ("Hauptfenster"), null, "gtk-home");
			this.homeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hauptfenster");
			w1.Add (this.homeAction, null);
			this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("dem Projekt zuweisen"), null, "gtk-add");
			this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("dem Projekt zuweisen");
			w1.Add (this.addAction, null);
			this.infoAction = new global::Gtk.Action ("infoAction", global::Mono.Unix.Catalog.GetString ("Information"), null, "gtk-info");
			this.infoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Information");
			w1.Add (this.infoAction, null);
			this.infoAction1 = new global::Gtk.Action ("infoAction1", global::Mono.Unix.Catalog.GetString ("Übersicht"), null, "gtk-info");
			this.infoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Übersicht");
			w1.Add (this.infoAction1, null);
			this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Bearbeiten"), null, "gtk-edit");
			this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
			w1.Add (this.editAction, null);
			this.editAction2 = new global::Gtk.Action ("editAction2", global::Mono.Unix.Catalog.GetString ("Bearbeiten"), null, "gtk-edit");
			this.editAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
			w1.Add (this.editAction2, null);
			this.printAction1 = new global::Gtk.Action ("printAction1", global::Mono.Unix.Catalog.GetString ("Drucken"), null, "gtk-print");
			this.printAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Drucken");
			w1.Add (this.printAction1, null);
			this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("in Excel exportieren"), null, "gtk-redo");
			this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("in Excel exportieren");
			w1.Add (this.redoAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "CustomerManager.SpecificWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Projektfenster");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(9));
			// Container child CustomerManager.SpecificWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='DateiAction' action='DateiAction'><menuitem name='homeAction' action='homeAction'/></menu><menu name='ProjekAction' action='ProjekAction'><menuitem name='dialogInfoAction1' action='dialogInfoAction1'/><menuitem name='editAction1' action='editAction1'/><menuitem name='mediaStopAction' action='mediaStopAction'/></menu><menu name='ZeitAction' action='ZeitAction'><menuitem name='infoAction1' action='infoAction1'/><menuitem name='editAction' action='editAction'/><menuitem name='printAction1' action='printAction1'/><menuitem name='redoAction' action='redoAction'/></menu><menu name='LieferantAction' action='LieferantAction'><menuitem name='addAction' action='addAction'/></menu><menu name='KundeAction' action='KundeAction'><menuitem name='infoAction' action='infoAction'/><menuitem name='editAction2' action='editAction2'/></menu><menu name='RechnungAction' action='RechnungAction'><menuitem name='printPreviewAction' action='printPreviewAction'/><menuitem name='printAction' action='printAction'/></menu><menu name='HilfeAction' action='HilfeAction'/></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='homeAction' action='homeAction'/><separator/><toolitem name='dialogInfoAction1' action='dialogInfoAction1'/><toolitem name='printPreviewAction' action='printPreviewAction'/><separator/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.hbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toolbar1]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.hbox1.Add (this.image2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image2]));
			w4.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.projectTitelLabel = new global::Gtk.Label ();
			this.projectTitelLabel.WidthRequest = 487;
			this.projectTitelLabel.HeightRequest = 52;
			this.projectTitelLabel.Name = "projectTitelLabel";
			this.projectTitelLabel.Xalign = 0F;
			this.projectTitelLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("PROJEKTTITEL");
			this.vbox6.Add (this.projectTitelLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.projectTitelLabel]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.HeightRequest = 12;
			this.hseparator1.Name = "hseparator1";
			this.vbox6.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.timeLabel = new global::Gtk.Label ();
			this.timeLabel.WidthRequest = 276;
			this.timeLabel.Name = "timeLabel";
			this.timeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Stempelung");
			this.vbox12.Add (this.timeLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.timeLabel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.HeightRequest = 12;
			this.hseparator4.Name = "hseparator4";
			this.vbox12.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hseparator4]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.endButton = new global::Gtk.Button ();
			this.endButton.WidthRequest = 145;
			this.endButton.CanFocus = true;
			this.endButton.Name = "endButton";
			this.endButton.UseUnderline = true;
			// Container child endButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_media-stop", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Ende");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.endButton.Add (w10);
			this.table3.Add (this.endButton);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.endButton]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.endLabel = new global::Gtk.Label ();
			this.endLabel.WidthRequest = 90;
			this.endLabel.Name = "endLabel";
			this.endLabel.Xalign = 1F;
			this.endLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Endzeit:");
			this.table3.Add (this.endLabel);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.endLabel]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.endtimeLabel = new global::Gtk.Label ();
			this.endtimeLabel.WidthRequest = 100;
			this.endtimeLabel.Name = "endtimeLabel";
			this.endtimeLabel.Xalign = 0F;
			this.table3.Add (this.endtimeLabel);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.endtimeLabel]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.startButton = new global::Gtk.Button ();
			this.startButton.WidthRequest = 145;
			this.startButton.CanFocus = true;
			this.startButton.Name = "startButton";
			this.startButton.UseUnderline = true;
			// Container child startButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_media-play", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.startButton.Add (w21);
			this.table3.Add (this.startButton);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.startButton]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.startLabel = new global::Gtk.Label ();
			this.startLabel.WidthRequest = 90;
			this.startLabel.Name = "startLabel";
			this.startLabel.Xalign = 1F;
			this.startLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Startzeit:");
			this.table3.Add (this.startLabel);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3 [this.startLabel]));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.starttimeLabel = new global::Gtk.Label ();
			this.starttimeLabel.WidthRequest = 100;
			this.starttimeLabel.Name = "starttimeLabel";
			this.starttimeLabel.Xalign = 0F;
			this.table3.Add (this.starttimeLabel);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.starttimeLabel]));
			w31.LeftAttach = ((uint)(2));
			w31.RightAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox12.Add (this.table3);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.table3]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox3.Add (this.vbox12);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox12]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox3.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator2]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.projectdescriptionLabel = new global::Gtk.Label ();
			this.projectdescriptionLabel.Name = "projectdescriptionLabel";
			this.projectdescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Projektbeschreibung");
			this.vbox11.Add (this.projectdescriptionLabel);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.projectdescriptionLabel]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.HeightRequest = 12;
			this.hseparator2.Name = "hseparator2";
			this.vbox11.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hseparator2]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ProjectDescriptionTextView = new global::Gtk.TextView ();
			this.ProjectDescriptionTextView.WidthRequest = 300;
			this.ProjectDescriptionTextView.HeightRequest = 130;
			this.ProjectDescriptionTextView.CanFocus = true;
			this.ProjectDescriptionTextView.Name = "ProjectDescriptionTextView";
			this.ProjectDescriptionTextView.Editable = false;
			this.ProjectDescriptionTextView.CursorVisible = false;
			this.ProjectDescriptionTextView.AcceptsTab = false;
			this.ProjectDescriptionTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.ProjectDescriptionTextView);
			this.vbox11.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.GtkScrolledWindow1]));
			w38.Position = 2;
			this.hbox3.Add (this.vbox11);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox11]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox6.Add (this.hbox3);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox3]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.descriptionLabel = new global::Gtk.Label ();
			this.descriptionLabel.Name = "descriptionLabel";
			this.descriptionLabel.Xalign = 1F;
			this.descriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Tätigkeit:");
			this.hbox4.Add (this.descriptionLabel);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.descriptionLabel]));
			w42.Position = 0;
			w42.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.HeightRequest = 98;
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.hbox4.Add (this.textview2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.textview2]));
			w43.Position = 1;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.HeightRequest = 20;
			this.hseparator5.Name = "hseparator5";
			this.vbox13.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hseparator5]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.terminLabel = new global::Gtk.Label ();
			this.terminLabel.Name = "terminLabel";
			this.terminLabel.Xalign = 0F;
			this.terminLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Terminübersicht");
			this.vbox13.Add (this.terminLabel);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.terminLabel]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator ();
			this.hseparator7.HeightRequest = 6;
			this.hseparator7.Name = "hseparator7";
			this.vbox14.Add (this.hseparator7);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hseparator7]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.eDateLabel = new global::Gtk.Label ();
			this.eDateLabel.Name = "eDateLabel";
			this.eDateLabel.Xalign = 0F;
			this.eDateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Enddatum:");
			this.table4.Add (this.eDateLabel);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4 [this.eDateLabel]));
			w48.TopAttach = ((uint)(1));
			w48.BottomAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.enddateBarLabel = new global::Gtk.Label ();
			this.enddateBarLabel.Name = "enddateBarLabel";
			this.enddateBarLabel.Xalign = 1F;
			this.enddateBarLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Ende");
			this.table4.Add (this.enddateBarLabel);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table4 [this.enddateBarLabel]));
			w49.TopAttach = ((uint)(3));
			w49.BottomAttach = ((uint)(4));
			w49.LeftAttach = ((uint)(2));
			w49.RightAttach = ((uint)(3));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.enddateLabel = new global::Gtk.Label ();
			this.enddateLabel.Name = "enddateLabel";
			this.enddateLabel.Xalign = 0F;
			this.enddateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ENDDATE");
			this.table4.Add (this.enddateLabel);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table4 [this.enddateLabel]));
			w50.TopAttach = ((uint)(1));
			w50.BottomAttach = ((uint)(2));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 10;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.table4.Add (this.fixed1);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed1]));
			w51.TopAttach = ((uint)(2));
			w51.BottomAttach = ((uint)(3));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 10;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table4.Add (this.fixed2);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed2]));
			w52.TopAttach = ((uint)(2));
			w52.BottomAttach = ((uint)(3));
			w52.LeftAttach = ((uint)(2));
			w52.RightAttach = ((uint)(3));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.HeightRequest = 10;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.table4.Add (this.fixed3);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed3]));
			w53.TopAttach = ((uint)(2));
			w53.BottomAttach = ((uint)(3));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sDateLabel = new global::Gtk.Label ();
			this.sDateLabel.Name = "sDateLabel";
			this.sDateLabel.Xalign = 0F;
			this.sDateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Startdatum:");
			this.table4.Add (this.sDateLabel);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table4 [this.sDateLabel]));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.startdateBarLabel = new global::Gtk.Label ();
			this.startdateBarLabel.Name = "startdateBarLabel";
			this.startdateBarLabel.Xalign = 0F;
			this.startdateBarLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			this.table4.Add (this.startdateBarLabel);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table4 [this.startdateBarLabel]));
			w55.TopAttach = ((uint)(3));
			w55.BottomAttach = ((uint)(4));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.startdateLabel = new global::Gtk.Label ();
			this.startdateLabel.Name = "startdateLabel";
			this.startdateLabel.Xalign = 0F;
			this.startdateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("STARTDATE");
			this.table4.Add (this.startdateLabel);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table4 [this.startdateLabel]));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox14.Add (this.table4);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.table4]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.TimeHscale = new global::Gtk.HScale (null);
			this.TimeHscale.Name = "TimeHscale";
			this.TimeHscale.Adjustment.Upper = 100;
			this.TimeHscale.Adjustment.PageIncrement = 10;
			this.TimeHscale.Adjustment.StepIncrement = 1;
			this.TimeHscale.Adjustment.Value = 74.3511450381679;
			this.TimeHscale.DrawValue = false;
			this.TimeHscale.Digits = -1;
			this.TimeHscale.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox14.Add (this.TimeHscale);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.TimeHscale]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			this.vbox13.Add (this.vbox14);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox14]));
			w59.Position = 2;
			w59.Expand = false;
			w59.Fill = false;
			this.vbox4.Add (this.vbox13);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox13]));
			w60.Position = 2;
			w60.Expand = false;
			w60.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w61.Position = 0;
			w61.Expand = false;
			w61.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox2.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator1]));
			w62.Position = 1;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.TimesLabel = new global::Gtk.Label ();
			this.TimesLabel.WidthRequest = 360;
			this.TimesLabel.Name = "TimesLabel";
			this.TimesLabel.Xalign = 0F;
			this.TimesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Stempelungen");
			this.vbox8.Add (this.TimesLabel);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.TimesLabel]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.HeightRequest = 12;
			this.hseparator3.Name = "hseparator3";
			this.vbox8.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator3]));
			w64.Position = 1;
			w64.Expand = false;
			w64.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox8.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow]));
			w66.Position = 2;
			this.hbox2.Add (this.vbox8);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox8]));
			w67.Position = 2;
			w67.Expand = false;
			w67.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator8 = new global::Gtk.HSeparator ();
			this.hseparator8.HeightRequest = 12;
			this.hseparator8.Name = "hseparator8";
			this.vbox1.Add (this.hseparator8);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator8]));
			w69.Position = 3;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.gesPriceLabel = new global::Gtk.Label ();
			this.gesPriceLabel.WidthRequest = 80;
			this.gesPriceLabel.Name = "gesPriceLabel";
			this.gesPriceLabel.Xalign = 1F;
			this.gesPriceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
			this.table5.Add (this.gesPriceLabel);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table5 [this.gesPriceLabel]));
			w70.LeftAttach = ((uint)(1));
			w70.RightAttach = ((uint)(2));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hourGesLabel = new global::Gtk.Label ();
			this.hourGesLabel.WidthRequest = 80;
			this.hourGesLabel.Name = "hourGesLabel";
			this.hourGesLabel.Xalign = 1F;
			this.hourGesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
			this.table5.Add (this.hourGesLabel);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table5 [this.hourGesLabel]));
			w71.TopAttach = ((uint)(1));
			w71.BottomAttach = ((uint)(2));
			w71.LeftAttach = ((uint)(1));
			w71.RightAttach = ((uint)(2));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hourPricegesLabel = new global::Gtk.Label ();
			this.hourPricegesLabel.WidthRequest = 80;
			this.hourPricegesLabel.Name = "hourPricegesLabel";
			this.hourPricegesLabel.Xalign = 1F;
			this.hourPricegesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
			this.table5.Add (this.hourPricegesLabel);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table5 [this.hourPricegesLabel]));
			w72.TopAttach = ((uint)(2));
			w72.BottomAttach = ((uint)(3));
			w72.LeftAttach = ((uint)(1));
			w72.RightAttach = ((uint)(2));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hourPriceLabel = new global::Gtk.Label ();
			this.hourPriceLabel.WidthRequest = 80;
			this.hourPriceLabel.Name = "hourPriceLabel";
			this.hourPriceLabel.Xalign = 1F;
			this.hourPriceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
			this.table5.Add (this.hourPriceLabel);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table5 [this.hourPriceLabel]));
			w73.TopAttach = ((uint)(3));
			w73.BottomAttach = ((uint)(4));
			w73.LeftAttach = ((uint)(1));
			w73.RightAttach = ((uint)(2));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Gesamtbetrag:");
			this.table5.Add (this.label17);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table5 [this.label17]));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Gesamtstunden:");
			this.table5.Add (this.label18);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table5 [this.label18]));
			w75.TopAttach = ((uint)(1));
			w75.BottomAttach = ((uint)(2));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Materialkosten:");
			this.table5.Add (this.label19);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table5 [this.label19]));
			w76.TopAttach = ((uint)(4));
			w76.BottomAttach = ((uint)(5));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 1F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Stundensatz:");
			this.table5.Add (this.label20);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table5 [this.label20]));
			w77.TopAttach = ((uint)(3));
			w77.BottomAttach = ((uint)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.WidthRequest = 30;
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("€");
			this.table5.Add (this.label21);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table5 [this.label21]));
			w78.LeftAttach = ((uint)(2));
			w78.RightAttach = ((uint)(3));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.WidthRequest = 30;
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("h");
			this.table5.Add (this.label22);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table5 [this.label22]));
			w79.TopAttach = ((uint)(1));
			w79.BottomAttach = ((uint)(2));
			w79.LeftAttach = ((uint)(2));
			w79.RightAttach = ((uint)(3));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.WidthRequest = 30;
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("€");
			this.table5.Add (this.label23);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table5 [this.label23]));
			w80.TopAttach = ((uint)(4));
			w80.BottomAttach = ((uint)(5));
			w80.LeftAttach = ((uint)(2));
			w80.RightAttach = ((uint)(3));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.WidthRequest = 30;
			this.label24.Name = "label24";
			this.label24.Xalign = 0F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("€");
			this.table5.Add (this.label24);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table5 [this.label24]));
			w81.TopAttach = ((uint)(3));
			w81.BottomAttach = ((uint)(4));
			w81.LeftAttach = ((uint)(2));
			w81.RightAttach = ((uint)(3));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.Xalign = 1F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Gesamtbetrag der Stunden:");
			this.table5.Add (this.label29);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table5 [this.label29]));
			w82.TopAttach = ((uint)(2));
			w82.BottomAttach = ((uint)(3));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label ();
			this.label30.WidthRequest = 30;
			this.label30.Name = "label30";
			this.label30.Xalign = 0F;
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("€");
			this.table5.Add (this.label30);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table5 [this.label30]));
			w83.TopAttach = ((uint)(2));
			w83.BottomAttach = ((uint)(3));
			w83.LeftAttach = ((uint)(2));
			w83.RightAttach = ((uint)(3));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.materialPriceLabel = new global::Gtk.Label ();
			this.materialPriceLabel.WidthRequest = 80;
			this.materialPriceLabel.Name = "materialPriceLabel";
			this.materialPriceLabel.Xalign = 1F;
			this.materialPriceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
			this.table5.Add (this.materialPriceLabel);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table5 [this.materialPriceLabel]));
			w84.TopAttach = ((uint)(4));
			w84.BottomAttach = ((uint)(5));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table5);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table5]));
			w85.Position = 4;
			w85.Expand = false;
			w85.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1073;
			this.DefaultHeight = 840;
			this.Show ();
		}
	}
}
